"""Pull the live title/description/canonical for every URL, so the rebuilt
site keeps exactly the metadata Google already has indexed."""
import json, os, re, subprocess, html, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
D    = os.path.join(ROOT, '.data')
LIVE = 'https://argflex.co.uk'
OUT  = os.path.join(D, 'live_html')
os.makedirs(OUT, exist_ok=True)

products   = json.load(open(os.path.join(D, 'products.json'),   encoding='utf-8'))
categories = json.load(open(os.path.join(D, 'categories.json'), encoding='utf-8'))
posts      = json.load(open(os.path.join(D, 'posts.json'),      encoding='utf-8'))

cat_by_id = {c['id']: c for c in categories}
def cat_path(c):
    p = cat_by_id.get(c['parent'])
    return f"{p['slug']}/{c['slug']}" if p else c['slug']

paths = ['/', '/shop/', '/blog/', '/about-us/', '/contacts/', '/refund_returns/',
         '/cart/', '/checkout/', '/wishlist/', '/compare/', '/my-account/']
paths += [f"/product-category/{cat_path(c)}/" for c in categories]
paths += [f"/product/{p['slug']}/"            for p in products]
paths += [f"/{p['slug']}/"                    for p in posts]

def slugify(path):
    return (path.strip('/').replace('/', '__') or 'home') + '.html'

# ---------------------------------------------------------------- download
todo = [p for p in paths if not os.path.exists(os.path.join(OUT, slugify(p)))]
print(f'{len(paths)} urls, {len(todo)} to download')
if todo:
    listing = os.path.join(D, '_seo_urls.txt')
    with open(listing, 'w', newline='\n', encoding='utf-8') as f:
        for p in todo:
            f.write(f'{LIVE}{p}\toutput={os.path.join(OUT, slugify(p))}\n')
    for i, p in enumerate(todo, 1):
        dest = os.path.join(OUT, slugify(p))
        subprocess.run(['curl', '-sS', '-L', '--max-time', '45', '-o', dest,
                        '-A', 'Mozilla/5.0 (compatible; ArgFlexMigration/1.0)', LIVE + p],
                       capture_output=True)
        if i % 10 == 0:
            print(f'  {i}/{len(todo)}', flush=True)

# ------------------------------------------------------------------- parse
def grab(pattern, src, group=1):
    m = re.search(pattern, src, re.I | re.S)
    return html.unescape(m.group(group).strip()) if m else ''

seo, missing_title, missing_desc = {}, [], []
for p in paths:
    f = os.path.join(OUT, slugify(p))
    if not os.path.exists(f) or os.path.getsize(f) < 500:
        missing_title.append(p)
        continue
    src = open(f, encoding='utf-8', errors='replace').read()
    head = src[:src.lower().find('</head>') + 7] if '</head>' in src.lower() else src[:60000]

    entry = {
        'title': grab(r'<title[^>]*>(.*?)</title>', head),
        'description': grab(r'<meta\s+name=["\']description["\']\s+content=["\'](.*?)["\']\s*/?>', head)
                    or grab(r'<meta\s+content=["\'](.*?)["\']\s+name=["\']description["\']\s*/?>', head),
        'canonical': grab(r'<link\s+rel=["\']canonical["\']\s+href=["\'](.*?)["\']', head),
        'og_title': grab(r'<meta\s+property=["\']og:title["\']\s+content=["\'](.*?)["\']', head),
        'og_description': grab(r'<meta\s+property=["\']og:description["\']\s+content=["\'](.*?)["\']', head),
        'og_image': grab(r'<meta\s+property=["\']og:image["\']\s+content=["\'](.*?)["\']', head),
        'robots': grab(r'<meta\s+name=["\']robots["\']\s+content=["\'](.*?)["\']', head),
    }
    # Yoast appends the site name; keep the title exactly as served
    if not entry['title']:
        missing_title.append(p)
    if not entry['description']:
        missing_desc.append(p)
    seo[p] = {k: v for k, v in entry.items() if v}

# ------------------------------------------------------------------- write
def php_val(v, indent=0):
    pad = '    ' * indent
    if isinstance(v, dict):
        if not v: return '[]'
        inner = ',\n'.join(f"{pad}    '{k}' => {php_val(x, indent+1)}" for k, x in v.items())
        return '[\n' + inner + ',\n' + pad + ']'
    s = str(v).replace('\\', '\\\\').replace("'", "\\'")
    return "'" + s + "'"

path = os.path.join(ROOT, 'data', 'seo.php')
with open(path, 'w', encoding='utf-8', newline='\n') as f:
    f.write("<?php\n/**\n * Titles, descriptions and canonicals exactly as the live WordPress site\n"
            " * serves them, so the rebuild keeps the metadata Google already indexed.\n"
            " * Generated by .data/fetch_seo.py - do not edit by hand.\n */\nreturn ")
    f.write(php_val(seo))
    f.write(";\n")

print(f'\ndata/seo.php: {os.path.getsize(path)} bytes, {len(seo)} urls')
print(f'with title      : {sum(1 for v in seo.values() if v.get("title"))}')
print(f'with description: {sum(1 for v in seo.values() if v.get("description"))}')
print(f'with canonical  : {sum(1 for v in seo.values() if v.get("canonical"))}')
if missing_title: print(f'NO TITLE ({len(missing_title)}):', missing_title[:8])
if missing_desc:  print(f'no description ({len(missing_desc)}):', missing_desc[:12])
